name: gdtoolkit-runner.yml

# Triggers the workflow on push but only for the main branch, or on demand for any branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install gdtoolkit
        
      # for all .gd files, run `gdformat filepath` in bash
      - name: execute gdformat
        run: find . -name "*.gd" -exec sh -c 'gdformat "$0"' {} \; 

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Let the code elf take a look.
          committer: Github <noreply@github.com>
          author: Github <noreply@github.com>
          signoff: false
          branch: gdformatter
          delete-branch: true
          title: 'Format GD script'
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
